### ISSUE TITLE
Fix chart colors

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#106]
# Feature Request

## Description

As a USER of the CaaS UI, I want to see charts in colours that are in harmony with the rest of the UI so that I have a better UX. 

### Assumption / Hypothesis
We believe that by improving the colour theme on the charts in the UI, users will be more attracted to read the content of the charts consequently enabling them to derive valuable actions on their connector context.  

## Which Areas Would Be Affected?

- edc-ui

## How does this tie into our current product?

> _Describe whether this request is related to an existing workflow, feature, or otherwise something in the product today. Or, does this open us up to new markets and innovative ideas?_

- Charts need three colours: "success", "failure", "in progress".
- Our charts colors are currently just some subset of a random chart color palette.
- These chart colors don't look in harmony when the connector is run in the yellow (MDS) variant
- Finding any colors that would is very hard if not impossible due to the MDS CD (white, black, yellow)

## Solution Proposal and Work Breakdown

- [ ] If not existing already, identify and document the locations of the UI where there are charts.
- [ ] Limit chart colors to three for now.
- [ ] Make chart colors theme-dependent.
- [ ] Find good colors for Sovity Theme
- [ ] Find good colors for MDS Theme

**Comment by AbdullahMuk** [comment]
removed from Sprint 35. Priority should be reviewed in context of the product backlog.

**Comment by kulgg** [comment]
Consider the chart colors in authority portal as they look pretty good. They are tailwind equivalents
