### ISSUE TITLE
Chrome suggests passwords for policy IDs

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#177]
# Bug Report

## Description

![image](https://user-images.githubusercontent.com/30114507/223964128-1a317e9c-b8d2-4b88-89f5-4db603d710cb.png)

### Expected Behavior

This field should have no autocomplete.

## Possible Implementation and Work Breakdown

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

- [ ] Try fix this field
- [ ] Quickly skim over other fields to find other similar fields (ID fields?) that should not have an autocomplete, and try to ensure no browsers try anything funny with those fields either.

**Comment by SebastianOpriel** [comment]
I have no idea, why chrome suggested the password. I miss a type="text" attribute in HTML. Maybe that's the root cause. I think, that the password dialog was not shown the second time, I created a policy. So: Please try to reproduce first

**Comment by AnurosePrakash** [comment]
I tried recreating the issue in the lower region. As mentioned by SO, the suggestion for a password comes once when we open the dialog box for the first time or if we previously entered some password field. 

On analysis, I could find that there is an inconsistency with chrome in this password suggestion/ autofill behavior. Nevertheless, a similar bug was reported in the resource -  https://stackoverflow.com/questions/35448269/angular-materials-can-you-disable-the-autocomplete-suggestions-for-an-input

There are many suggestions to solve this issue. One suggestion is to use autocomplete as off in the input tag. However, it does not seem not to work always. As part of the working solution, autocomplete field was set as '<some text>' in the suggestions and it worked on the site (https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_autocomplete) as in the attachment.
 
![testing_autofill](https://user-images.githubusercontent.com/108627760/224754502-140b1b93-f48c-4285-a1a1-849d8973511c.png)
