### ISSUE TITLE
Connector Version Info

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#199]
# Feature Request

## Description

Right now we have a developer utility of  being able to find out the git status of our deployed connectors;
- Our UI has  `/assets/config/version.txt`
  - See https://sovity-demo-edc-ui.stage-sovity.azure.sovity.io/assets/config/version.txt
- Our EDCs use the last-commit-info extension which provides on the management endpoint: `/last-commit-info`:
  - Contains the EDC last commit info
  - Contains the EDC Extension JARs last commit info (possibly hidden for our CEs where EDC version == edc-extensions version)
  - See https://github.com/sovity/edc-extensions/tree/main/extensions/last-commit-info#about-this-extension
  - See https://sovity-demo-edc-ui.stage-sovity.azure.sovity.io/control/data/last-commit-info (broken right now)

Our goal now is to show these in our UI for debugging purposes.

## Which Areas Would Be Affected?

- CI Pipeline
- Last commit info extension
- UI

## Why Is the Feature Desired?

Convenience

## Stakeholders

@SebastianOpriel 

## Solution Proposal and Work Breakdown

- [x] https://github.com/sovity/PMO-Software/issues/162
- [x] Additional Dashboard Card or additional property grid group for Connector Versions
  - [x] Show commit date for now.
  - [x] Clicking on it should show the Last Commit Info

**Comment by SebastianOpriel** [comment]
Version: IMAGE_VERSION (DATE)

**Comment by SebastianOpriel** [comment]
@AnurosePrakash can the issue be closed?

**Comment by AnurosePrakash** [comment]
@richardtreier Can you please take up changes to be done in the backend

**Comment by richardtreier** [comment]
There is still a bug, but the initial implementation issue can be gladly closed: https://github.com/sovity/edc-extensions/issues/420
