### ISSUE TITLE
Certificate Public Key & Valid Until as Additional Connector Properties

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#201]
# Feature Request

## Description

Connector Self-Info should contain:
- Certificate Public Key
- Certificate Valid Until

## Which Areas Would Be Affected?

UI, Extension: EDC UI Config

## Solution Proposal and Work Breakdown

- [ ] Create two new EDC UI propertiers
- [ ] Update local dev .env
- [ ] Add properties to dashboard
- [ ] Update Extension: UI Config

**Comment by SebastianOpriel** [comment]
I wouldn't add properties (`Create two new EDC UI propertiers`). These information shall be served from EDC directly.

**Comment by SebastianOpriel** [comment]
Information shall be added to current setting section on Dashboard
