### ISSUE TITLE
Integrate OpenApi Code Generation from EDC MS7 (API wrapper)

### ISSUE THREAD

**Issue by efiege** [sovity/edc-ui#24]
# Feature Request

## Type of Issue
Enhancement

## Describe the ideal solution or feature request
Use OpenApi file to generate mgmt-client. Don't commit generated code into repository.

## Solution Proposal
- [ ] Remove generated mgmt-client code
- [x] Create a OpenApi specification file for m7-EDC
- [ ] Add new Open-API codegen:
  - [ ] Find new generator / generator target that works better for our use case.
    - generated files should not have to be touched anymore
    - Centralized setting of X-Api-Key should be easy.
  - [ ] Add new codegen.
  - [ ] Add new codegen target to gitignore.
  - [ ] Adopt Dockerfile to also run codegen, decide whether to run codegen in: postinstall, pre-serve, make it work with Docker container

**Comment by efiege** [comment]
[openapi.yaml.txt](https://github.com/sovity/edc-ui/files/10465835/openapi.yaml.txt)

**Comment by richardtreier** [comment]
Yaml unterstützt Kommentare, kannst du mir sagen, was wir über die oberste Zeile im openapi.yaml schreiben sollten, damit wir beim nächsten Mal gut verstehen können, von welcher Version diese yaml istß

**Comment by SebastianOpriel** [comment]
@richardtreier take following issues into account
- https://github.com/sovity/PMO-Software/issues/92
- https://github.com/sovity/PMO-Software/issues/93

**Comment by richardtreier** [comment]
closed in favor of https://github.com/sovity/edc-extensions/issues/183
