### ISSUE TITLE
Contract Definitions Cards not showing if left expression is not on asset:id property

### ISSUE THREAD

**Issue by rafaelmagalhaes-ctw** [sovity/edc-ui#243]
# Bug Report

## Description

If a contract definition is created using the DMA directly an not the UI, and the user uses a specific property to agregate its assets (i.e. asset:prop:usecase), the contract definitions cards are not parsed correctly.

### Expected Behavior

The UI should be able to, from the contract definition criteria, identify which assets are tied to the CD even if the left expression is not on the "asset:prop:id".

### Observed Behavior

The UI throws an error and console logs "o.map is not a function".

## Steps to Reproduce

Create two assets with a custom asset:prop:usecase = "sovity" property.
Create a contract definition with criteria leftexpression "asset:prop:usecase" and rightexpression "sovity".
Check the UI contract definitions tab.

## Context Information

A user might register their artifacts using an automated method and not the UI. It also might need to aggregate its assets using a custom asset property and then create a contract definition on the same property.

**Comment by richardtreier** [comment]
will be fixed in https://github.com/sovity/edc-ui/pull/259
