### ISSUE TITLE
Better "Connected Dataspace" Info

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#253]
# Feature Request

## Description

Right now our connector displays the DAPS Token URL and DAPS JWKS URL.

The idea is to replace this information with a more dedicated "You are connected to dataspace XYZ" message or something similar.

Possible Ideas:
- Add a new box with a green light: "You are connected to Mobility Dataspace." on the dashboard.
- Replace DAPS Property in Connector Properties with a single clickable "Dataspace: Mobility Dataspace" which will then show a detail dialog that will contain the DAPS URLs.
- Just add another property "Connected Dataspace" next to these technical URLs (easiest)
- ...

## Which Areas Would Be Affected?

UI, existing deployments (new UI Property), portals (new UI Property)

## Why Is the Feature Desired?

The current DAPS properties shown are both technical and not very helpful to non-technical people.

## Stakeholders

@sebk46 

## Solution Proposal and Work Breakdown

- [ ] Add new UI Property for the connected dataspace name
- [ ] Implement a nice way of displaying the connected data space
- [ ] Add the need to migrate existing connectors to include the data space name in the issue for the next product release.
- [ ] Add the default data space name to our Staging and Production Portal settings.

**Comment by SebastianOpriel** [comment]
I would like to postpone this, to a point, where this is a requirement from users.

**Comment by sebk46** [comment]
Yes, something for the backlog.

**Comment by SebastianOpriel** [comment]
not really necessary, only a nice to have.
