### ISSUE TITLE
Allow open ended date intervals

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#283]
# Feature Request

## Description

Currently our time-restricted interval requires two dates. Internally it creates a policy with two permissions (START <= TODAY and TODAY < END). There is a customer that would like to be able to specify the date range as open-ended. 

Our goal is to support the setting of open-ended time restricted policies in a transparent way for the user.

## Stakeholders

MDS

## Solution Proposal and Work Breakdown

- Possible solution A: 
  - [ ] Add a checkbox that replaces the interval selection with a date selection when set.
- Possible solution B: 
  - [ ] Find a way to make the date interval selection allow setting of open ended intervals (might not work)
- ...

**Comment by MoritzStober-acatech** [comment]
Hi is this feature available? If so which option was implemented? Thank you

**Comment by richardtreier** [comment]
> Hi is this feature available? If so which option was implemented? Thank you

Hi, we found a way to make the component accept just the start date, so not setting the end date should work fine, now.
