### ISSUE TITLE
Asset not displayable if a property is an object

### ISSUE THREAD

**Issue by gabrielfriedel** [sovity/edc-ui#322]
# Bug Report

## Description

Creating an asset which contains an object as property causes the edc-ui to display an empty box instead of the asset.
In version 0.0.1-milestone-8-sovity2 the asset was shown by the edc-ui, but without object.
After jumping to version 0.0.1-milestone-8-sovity5 the bug occured. Testing the issue with 0.0.1-milestone-8-sovity6 was also leading to the same behaviour.

According to the browser the asset was received correctly. The console has returned the errors shown in the following picture. Also the empty asset box can be seen.

![image](https://github.com/sovity/edc-ui/assets/137403088/85aa2999-b66e-4445-a8e8-012630a23eaf)

**Additional information:** The asset which contains the object was created with a script not the edc-ui.

### Expected Behavior

The asset will be show with all its properties, as well as the object (at least stringified)

### Observed Behavior

The asset ist not visible at all. Instead an empty box is shown.

## Steps to Reproduce

1. Create an asset via edc-API like:
`{{
    "asset": {
        "properties": {
            "asset:prop:name": "artifactname",
            "asset:prop:id": "artifactid",
            "asset:prop:contenttype": "application/json",
            "asset:prop:curatorOrganizationName": "mycurator",
            "asset:prop:originator": "myoriginator",
            "internal:config": {
                "name": "myname",
                "description": "mydescription",
                "parameter": [{
                        "name": "geoX",
                        "type": "double",
                        "optional": "false"
                    }, {
                        "name": "geoY",
                        "type": "double",
                        "optional": "false"
                    }
                ]
            }
        }
    },
    "dataAddress": {
		...
    }
}
`
2. Click on the created asset in the edc-ui

## Context Information

-   Used versions: 
    edc-ui: 0.0.1-milestone-8-sovity5
    edc-extensions: edc-ce-mds:3.2.0

**Comment by richardtreier** [comment]
Hi, for MS8 we will most likely not fix this issue.

We are currently working on the upgrade to the Core EDC Version 0.1.0 which will probably force us to make some decisions regarding how and what we support regarding the new JSON-LD APIs.

There we will address issues such as this one.

depends on https://github.com/sovity/edc-extensions/issues/391

**Comment by richardtreier** [comment]
Hi, this issue will be fixed by #364 and especially #459.

For our sovity EDC CE with Core EDC 0 we will stop using the management API and will also support extending assets by custom properties that contain complex objects.
