### ISSUE TITLE
Backend UI API Wrapper: Create Policy Definition Endpoint with 0.2.x

### ISSUE THREAD

**Issue by efiege** [sovity/edc-ui#331]
# Feature Request

## Description

Here is a comparison of the old and the new request:
![grafik](https://github.com/sovity/edc-ui/assets/105237007/5f63dea0-3217-463e-8545-a6a1109f7371)

## Solution Proposal and Work Breakdown

- [ ] Pass `@context` for `edc`and `odrl`
- [ ] Pass `"@type": "PolicyDefinitionDto"`
- [ ] Rewrite edc permissions to odrl permissions

**Comment by richardtreier** [comment]
Closed in favor of https://github.com/sovity/edc-ui/issues/332

**Comment by richardtreier** [comment]
duplicate https://github.com/sovity/edc-ui/issues/331
