### ISSUE TITLE
Backend UI API Wrapper: Negotiate Contract Endpoint with 0.2.x

### ISSUE THREAD

**Issue by efiege** [sovity/edc-ui#334]
# Feature Request

## Description

Dealing with JSON-LD in Angular templates does not work, so before we add an intermediate layer into our UI we want to deal with the JSON-LD in our UI API Wrapper. Thus we want to add a new endpoint to type safely use the EDC Version 0 APIs from our UI.

Here is a comparison of the old and the new request:
![grafik](https://github.com/sovity/edc-ui/assets/105237007/8864f854-5675-4a12-817f-f51244bd82f9)

## Solution Proposal and Work Breakdown
-   [ ]

**Comment by richardtreier** [comment]
done by https://github.com/sovity/edc-extensions/pull/525
