### ISSUE TITLE
Fix EDC UI Dockerfile

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#361]
# Feature Request

## Description

- [x] Fix the HEALTHCHECK of the Dockerfile. Careful, the health check is not called by docker-compose iirc, so you need to add the healthcheck manually to the docker-compose to test if it works.
- [ ] Fix a warning thrown by the nginx conf template not being removed after the templating is done. Sth like "access denied: default.conf.j2"

**Comment by SaadEGI** [comment]
![grafik](https://github.com/sovity/edc-ui/assets/25992003/4b944135-ef97-442e-9f29-30d7eee8f64d)
