### ISSUE TITLE
Add Screenshots to root README.md

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#362]
# Feature Request

## Description

Add screenshots for EDC UI in the README.md,

- [x] Something like "one row of three screenshots, with a link to see them large, one times the dashboard, one times the contract page, one times the asset creation dialog".
- [x] The screenshots should be located in "docs/screenshots".
- [x] Update the release template of this repository to contain detailed instructions on checking if the screenshots need to be updated, and how to update them with what if they do need to be changed.
- [x] This will be customer facing documentation, so we should make it nice, and let @SebastianOpriel review it.

**Comment by tmberthold** [comment]
Current status at sprint end:
- waiting for the PR review https://github.com/sovity/edc-ui/pull/566
