### ISSUE TITLE
Support Markdown for Description

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-ui#380]
The Description field should support Markdown Syntax and render it appropriately in Catalog and Asset Details Popups. 
- [ ] Markdown shall be supported
- [ ] Hints about Markdown shall be added to UI
- [ ] Render Markdown in views

Additionally we shall handle unsupported formatting via HTML-tags - or at least warn the user (e.g. via Hint).
![image](https://github.com/sovity/edc-ui/assets/22075788/cabd9d85-287d-4bae-9684-e5d7928030e5)

**Comment by richardtreier** [comment]
Closed in favor of https://github.com/sovity/edc-broker-server-extension/issues/323
