### ISSUE TITLE
[MS9+] Allowing updates on user-created entities

### ISSUE THREAD

**Issue by tmberthold** [sovity/edc-ui#400]
Beginning with MS9, the core-edc allows updating of assets, policydefinitions and Contractdefinitions via PUT. Maybe you should also enable that via "EDIT" of assets and so on in the UI?

https://github.com/eclipse-edc/Connector/tree/main/docs/developer/decision-records/2023-02-22-update-entities

**Comment by richardtreier** [comment]
closed in favor of https://github.com/sovity/edc-extensions/issues/606
