### ISSUE TITLE
Mechanism for data provider to guarantee availability of data source for time x

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-ui#425]
In a real-world, one doesn't want to rely on data and APIs which might be unavailable from next week on. We need a field or mechanism that assures the consumer, that they can rely on availability in the long-term.

**Comment by ununhexium** [comment]
If it's an external API for the provider, they have no control over that.
If it's an API that is internal to the provider, it's this already implied by a time-based policy?
