### ISSUE TITLE
Un-Escape URLs for REST endpoints

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-ui#439]
# Bug Report

### Observed Behavior

It is possible to enter URLs in Browsers with [escaped symbols](https://docs.microfocus.com/OMi/10.62/Content/OMi/ExtGuide/ExtApps/URL_encoding.htm) like `%3D` which is  `=`. The problem is, that the EDC doesn't properly handle such escaped URLs. Thus following URL doesn't work:
- https://api.sharedmobility.ch/v1/sharedmobility/identify?filters=ch.bfe.sharedmobility.vehicle_type%3DE-Bike&filters=ch.bfe.sharedmobility.pickup_type%3Dstation_based&Geometry=7.57699%2C47.55352&Tolerance=5000&offset=0&geometryFormat=esrijson

but this URL works:
- https://api.sharedmobility.ch/v1/sharedmobility/identify?filters=ch.bfe.sharedmobility.vehicle_type=E-Scooter&Geometry=8.72334,47.50024&Tolerance=500&offset=0&geometryFormat=esrijson

## Possible Implementation and Work Breakdown

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

-   [ ] Task 1
-   [ ] Task 2
-   ...

**Comment by AbdullahMuk** [comment]
@illfixit please cross-check if a solution for this topic has been released already.

- If YES, solution has been released already: close the issue (if possible reference the PR with which the solution was released. )
- if NO, solution has not been released already: please provide a fix for it (you can document your proposed implementation in the section "Possible Implementation and Work Breakdown"). 

For any technical clarifications please contact a relevant colleague in dev team; for non-technical clarifications, please contact me.

**Comment by AbdullahMuk** [comment]
Topic considered to have been delivered based on finding from Ilia: both variants work with Chrome and Firefox and show proper JSON.

**Comment by SebastianOpriel** [comment]
Maybe related: https://github.com/sovity/edc-extensions/issues/582

**Comment by SebastianOpriel** [comment]
@AbdullahMuk what was the reason for closing?
