### ISSUE TITLE
Divide Navigation Bar into Consuming and Providing sections

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-ui#465]
# Feature Request

## Description
I as a user want to have a clear separation of Providing and Consuming Data. 

## Which Areas Would Be Affected?
- Navigation Bar
- Separating all pages into consuming and providing

## Why Is the Feature Desired?
More clarity for end users

## Stakeholders
@sebk46 @SebastianOpriel @AbdullahMuk

## Solution Design and Work Breakdown

Solution design on Miro [HERE](https://miro.com/app/board/uXjVOGpeALM=/?moveToWidget=3458764598757217227&cot=14)

```[tasklist]
### Tasks
- [ ] Solution Design
- [ ] Implementation
- [ ] Functional Test
```

**Comment by AbdullahMuk** [comment]
A first iteration of this enhancement has been deployed with the release of [edc-ui v4.0.0](https://github.com/sovity/edc-ui/releases/tag/v4.0.0) however a refinement is required in a new iteration.
