### ISSUE TITLE
Check all other EDC Extensions documentation

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#479]
- Data Address properties have changed. They now use URLs as prefixes or they won't work: https://github.com/sovity/edc-extensions/blob/32bcaee88adbbadda148c55ec32e3f966723c283/utils/test-connector-remote/src/main/java/de/sovity/edc/extension/e2e/connector/DataTransferTestUtil.java#L47
- Asset properties have changed: [2023-08-30 Asset Property Migration.md](https://github.com/sovity/edc-ui/files/12605839/2023-08-30.Asset.Property.Migration.md)
- Other Management API requests might also have changed.

```[tasklist]
### Tasks
- [ ] Check all existing documentation's API calls and values
```

**Comment by tmberthold** [comment]
Guess following pages need to be updated:
- https://github.com/sovity/edc-extensions/blob/main/docs/getting-started/documentation/parameterized_assets.md
- https://github.com/sovity/edc-extensions/blob/main/docs/getting-started/documentation/oauth-data-address.md
