### ISSUE TITLE
Referring sovity in MDS CaaS version

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-ui#518]
# Feature Request

## Description
Add in hosted MDS Caas profile
- [ ]  a new box in dashboard "Provided by sovity" with sovity logo and a short text with trigger that can be upgraded for more power.
- [ ] Add at bottom right a "Powered by sovity" with logo like following 
![image](https://github.com/sovity/edc-ui/assets/22075788/40dbde83-3d02-4e33-98d4-45f6facf4d56)

## Which Areas Would Be Affected?
EDC UI

## Stakeholders
@sebk46 
@AbdullahMuk 

### a new box in dashboard "Provided by sovity" with sovity logo and a short text with trigger that can be upgraded for more power.

Implemented as be green circled area on Dashboard UI

![Image](https://github.com/sovity/edc-ui/assets/143605455/f255061d-ebc0-41b3-9c12-92a0837689c5)

### "Powered by sovity" branding
Option 1 is favoured for implementation.

![Image](https://github.com/sovity/edc-ui/assets/143605455/5aef6ac7-4036-4136-99ce-a823158f72b8)

**Reasoning:**

- Given that UI does not have a footer, overlay is not possible.
- Based on the user behaviour concept that users tend to scan websites in F-Pattern (more details from the Web **[HERE](https://cxl.com/blog/10-useful-findings-about-how-people-view-websites/#h-2-people-read-in-f-patterns)** ), Option 1 is most favourable in the positioning of the sovity brand.

**Comment by SebastianOpriel** [comment]
Let us use https://sovity.de/en/contact/ as this directly leads to english version

**Comment by illfixit** [comment]
I think it looks nice with logo in title?
![Screenshot 2023-11-02 185755](https://github.com/sovity/edc-ui/assets/66363651/65b3ada3-b7b3-4ed1-ad6e-99f2f944b121)

**Comment by illfixit** [comment]
New version

![Image](https://github.com/sovity/edc-ui/assets/66363651/d465ac0c-cab1-42b4-9247-c5d578189c90)

**Comment by illfixit** [comment]
Here's the latest version with small text changes

![image](https://github.com/sovity/edc-ui/assets/66363651/de46711f-3b16-49e3-8379-e13625ec7b0e)

**Comment by illfixit** [comment]
Provided bysovity logo
Basic Edition EDC
This EDC Connector on the subscription level "Basic" is provided by sovity to enable your first steps in the Mobility Data Space (MDS).

For additional features and advanced capacities, please feel free to contact us.

![image](https://github.com/sovity/edc-ui/assets/66363651/64850f07-9caf-41b0-a0b0-4e49bc064b35)

**Comment by AbdullahMuk** [comment]
@illfixit following consultation with SK, Option 3 is preferred because we understand that MDS would like to standardize across all their partners that proprietary logos (such as sovity's) appear at the bottom right.

Furthermore it is more valuable for the sovity brand that we make the logo persistent at the bottom right instead of appearing at the end of the page only after scrolling. Do you have some proposal how we might achieve this result?


![Image](https://github.com/sovity/edc-ui/assets/143605455/06722b11-4bbc-475e-bcf9-9fa34e7b867d)

**Comment by AbdullahMuk** [comment]
@illfixit responding to your questions here.

Option 3 should be displayed for all MDS profiles.

What about the possibility make the logo persistent at the bottom right instead of appearing at the end of the page only after scrolling. **Do you have some proposal how we might achieve this result?**

**Comment by SebastianOpriel** [comment]
I would not go with an overlay, if we have no footer. Either we need a footer or we would have it at the end of each page IMO

**Comment by AbdullahMuk** [comment]
@sebk46 @SeBuSov Following alignments with @illfixit, decision is we go with Option 1.

**Reasoning:** 
- Given that UI does not have a footer, overlay is not possible.
- Based on the user behaviour concept that users tend to scan websites in F-Pattern (more details from the Web **[HERE](https://cxl.com/blog/10-useful-findings-about-how-people-view-websites/#h-2-people-read-in-f-patterns)** ), Option 1 is most favourable in the positioning of the sovity brand.

**Comment by illfixit** [comment]
Glad that you liked my tip :)
I also switched the text style to italic like in the original image

![image](https://github.com/sovity/edc-ui/assets/66363651/9b665a7d-b7a4-40a0-b4b4-6c4b1c57accc)
