### ISSUE TITLE
fix auth proxy issues by disabling caching for non-static files

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#584]
# Feature Request

## Description

As a user, 
I want the system to properly handle page caching during logout,
So that I do not encounter a broken page due to the browser skipping the request.

## How does this tie into our current product?
This error occurs because the browsers cached the page, skipping the request, which would otherwise redirect to a keycloak browser flow.

We have an auth proxy for this otherwise unprotected UI image.

This request focuses on improving the user experience during logout and ensuring the security of the UI image. 

## Acceptance Criteria
- When user logs out, the system should invalidate the cache and redirect user to the keycloak browser flow.
- The system should ensure the UI image is protected via an auth proxy. @kulgg @richardtreier please validate if this is a valid acceptance criteria to keep.
- Implement solution across all variants of the CaaS. 

## Solution Proposal and Work Breakdown

The solution is to add the same thing we added for the authority portal in the EDC CE.

```[tasklist]
- [x] Update the nginx conf
```

@AbdullahMuk @kulgg

**Comment by richardtreier** [comment]
@kulgg

**Comment by kulgg** [comment]
I discovered another bug while working on this issue: https://github.com/sovity/edc-ui/issues/591
The /logout functionality does not work during local development (unrelated to nginx)

**Comment by kulgg** [comment]
This issue might be a misdiagnosis.
In the staging the environment the blank page is caused by the same NullInjectionError.
Here, the o probably refers to PreviousRouteListener (JS minimization in prod).

```
core.mjs:9171 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(o)[o -> o -> o -> o -> o]: 
  NullInjectorError: No provider for o!
```
