### ISSUE TITLE
Enhance format of validity on Contract Definitions page

### ISSUE THREAD

**Issue by AbdullahMuk** [sovity/edc-ui#594]
![image](https://github.com/sovity/edc-ui/assets/143605455/ec01caa9-1e64-4c69-b455-01021dd2c815)

**Comment by AbdullahMuk** [comment]
@simritbhatia please find out whether the current format is intended.

If the current format is not intended, we should improve the format.

**Comment by SebastianOpriel** [comment]
You refer to an internal representation of the EDC's data. The representation as it is shown here, is pretty fine for a JSON and does not need any adjustment.
This would be a feature request to enhance the overview tile behind the popup to display a nice validity format
