### ISSUE TITLE
[Filters on Contracts Page] Design mockups / prototypes

### ISSUE THREAD

**Issue by AbdullahMuk** [sovity/edc-ui#600]
# Description  

See Epic https://github.com/sovity/edc-ui/issues/589 for context. 

Simrit is designing the new UX / UI mockups / proposals on Figma **[HERE](https://www.figma.com/proto/NQ5XRHbKDO5OvKlY2B71ea/EDC-UX%2FUI-Analysis?page-id=0%3A1&type=design&node-id=207-403&viewport=1516%2C-2264%2C0.62&t=qqADd3xo6M66OwKA-1&scaling=contain&starting-point-node-id=133%3A2)**.

**Comment by simritbhatia** [comment]
ready for internal testing

**Comment by AbdullahMuk** [comment]
Based on internal testing with AM and SK, SiB updated the mockups. Parent ticket ready for discussion with Dev Team.
