### ISSUE TITLE
Frontend: Implement filters for contracts page

### ISSUE THREAD

**Issue by AbdullahMuk** [sovity/edc-ui#601]
## Description

See Epic https://github.com/sovity/edc-ui/issues/589 to understand the context. 
Backend: https://github.com/sovity/edc-extensions/issues/911

```[tasklist]
### Solution Proposal and Work Breakdown
- [ ] Switch contracts page to state management
- [ ] Implement Filter UI based on mockup in sovity/edc-ui#600
```

**Comment by AbdullahMuk** [comment]
@kulgg no action for you to take yet. I anticipate that you will work on this topic as early as Sprint 41; thus I tag you.

**Comment by kulgg** [comment]
@AbdullahMuk for this complex feature we first need support for filtering in the backend before frontend development can start.
