### ISSUE TITLE
Contract Definition Details Popup

### ISSUE THREAD

**Issue by simritbhatia** [sovity/edc-ui#635]
# Issue

## Description

![Frame 616 1](https://github.com/sovity/edc-ui/assets/144789714/bef9dbd0-8b3f-4e4a-b151-0513881e4d17)

The content of the popup is about setting access rights to contracts. These access rights can however be arbitrarly complex, because they may be a composition of any number of rules. For instance this could restrict the access to participation in a certain use-case "and" in a certain time period. You could also replace this "and" by an "or". This is what [odrl](https://www.w3.org/TR/odrl-model/) is about.
 
we need to figure out how to represent the complex structure of odrl into a dialog and probably best solution is to restrict the dialog to some subset functionalities of odrl. To solve this puzzle we have to decide, **which functionalities of odrl we want to have in the UI and to what degree they are relevant to the customer.**

### Requirements

_Which requirements do you have to be fulfilled?_

-   Figure out which parameters are relevant for technical and non-technical users
-   Discard the non-relevant parameters

```[tasklist]
### Tasks
- [ ] https://github.com/sovity/edc-ui/issues/593
- [ ] https://github.com/sovity/edc-ui/issues/594
```

**Comment by SebastianOpriel** [comment]
Since the rework brought a nice visual adjustment, we do not need to enhance the popup.
![image](https://github.com/user-attachments/assets/07963fea-800e-408b-bae0-692aa4deb982)
