### ISSUE TITLE
Implement Multi-Language Support / Localization

### ISSUE THREAD

**Issue by bearn01d** [sovity/edc-ui#680]
# Feature Request

## Description
To make the UI more accessible for diverse user groups, internationalization of the UI is beneficial, allowing for subsequent localizations. In a first step, a German version would be desired.

## How does this tie into our current product?
Currently, no internationalization is available in the frontend code.

### Requirements to achieve from this initiative:
- Design a solution that enables multiple localizations in the long-term. 
- Users should have the possibility to switch between multiple languages, at minimum between English and German.

## Solution Proposal and Work Breakdown
We implemented this at Fraunhofer FIT and would be interested in upstreaming this feature (i18n + localization to German), as already discussed with @SebastianOpriel. We are mostly ready to prepare a PR, if desired.

```[tasklist]
- [x] Fix the GitHub Projects Labels, Sprint and other Metadata
```

**Comment by tmberthold** [comment]
Hello and thank you for this offer!

I will bring this up internally to our PO (@AbdullahMuk) and, depending on the outcome, we will discuss it with the component owners of the edc-ui repo.

**Comment by bearn01d** [comment]
@tmberthold, are there news regarding this?

**Comment by tmberthold** [comment]
> We implemented this at Fraunhofer FIT and would be interested in upstreaming this feature

I ask for a little patience, I have pointed to this again internally.

**Comment by AbdullahMuk** [comment]
@bearn01d you make a great proposal and would love your contribution!

As a next step, indeed it would be great if you could prepare a PR. Once the PR is ready, we will do a review and align with you further; kindly note that as per our roadmap planning, we plan capacity for review as from beginning of April.

**Comment by bearn01d** [comment]
Great, we will prepare this, hopefully until the beginning of April.

**Comment by AbdullahMuk** [comment]
Feedback from contributor of the PR: we will need some more days for the adaption. With the new features merged recently, quite many things have changed quite fundamentally so we need to do larger adaptations. Given our main translation developer is out of office makes it even more difficult. Still, we do our best to port our translations asap.
