### ISSUE TITLE
asset-select.component.html: broken comparison

### ISSUE THREAD

**Issue by bearn01d** [sovity/edc-ui#684]
### Steps to Reproduce
The comparison of assets in the `asset-select` component is broken: https://github.com/sovity/edc-ui/blob/47c63828bce6936b76cbda82eebb34a7f0804c84/src/app/routes/connector-ui/contract-definition-page/asset-select/asset-select.component.html#L7
The problem is that `UiAssetMapped` has the field `assetId` but not an `id`. Therefore, the comparison is `undefined` with `undefined` and as such worthless. Changing to `assetId` would fix this.

**Comment by tmberthold** [comment]
Hi @bearn01d,
I got asked to ask you to please provide additional information in the issue-comment itself to follow our [Bug Report Template](https://github.com/sovity/edc-ui/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yaml) structure, could you please adapt the issue to follow the structure? I already added the structure elements to the issue itself.
