### ISSUE TITLE
HTTP Data Transfer: Headers not included in transfer request

### ISSUE THREAD

**Issue by bearn01d** [sovity/edc-ui#702]
# Bug Report

## Description

Additional headers specified in the UI are not included in the HTTP request made for transfer.
Apparently, EDC 0.2.1 requires the data sink property for the additional headers without the EDC namespace prefix added here: https://github.com/sovity/edc-ui/blob/23dfcb2efaf3fe68297ea1fa40a5304a74b461f2/src/app/core/services/models/data-address-properties.ts#L8.
Indeed, the EDC code checks whether the property `.startsWith("header:")`. Without the prefix, the header is included.

This can also be considered an EDC bug, but for version 0.2.1, it breaks the UI so might be worth a workaround in this repository, i.e. removing the prefix. For further properties, I didn't test the behavior yet.

### Expected Behavior

Headers specified in the UI should be added to the transfer HTTP request.

### Observed Behavior

The header is missing.

## Steps to reproduce:

1. Create an asset.
2. Create a contract definition.
3. Go to another connector and negotiate contract.
4. Try to make a transfer to a data sink that needs additional header.
5. Set the header name and header value.
6. Transfer data.
7. Check if the data was transferred and the header was set correctly during the transfer.

**Comment by AbdullahMuk** [comment]
Will be resolved with https://github.com/sovity/PMO-Software/issues/694

**Comment by SebastianOpriel** [comment]
@AbdullahMuk this cannot be closed yet.

@bearn01d do I get following steps correct?

**Steps to reproduce:**
1. Create an asset.
2. Create a contract definition.
3. Go to another connector and negotiate contract.
4. Try to make a transfer to a data sink that needs additional header. 
5. Set the header name and header value.
6. Transfer data.
7. Check if the data was transferred and the header was set correctly during the transfer.

**Comment by bearn01d** [comment]
@SebastianOpriel, yes, exactly, these are the steps I took.

**Comment by AbdullahMuk** [comment]
@tmberthold following the PR that Richard reviewed, please reproduce the scenario and confirm that the bug is not there anymore.

Then we can close this issue.

**Comment by tmberthold** [comment]
I followed the steps to reproduce and the header now reaches the data-sink when set during initiating the transfer. Fixed for me.

Have added a header "issue:702" for testing while initiating the transfer via the UI, the reach the data-sink.

![image](https://github.com/sovity/edc-ui/assets/75306992/136f9b77-f50e-4a68-8b14-6a86062f2235)
