### ISSUE TITLE
Path- and Query-Parameterization are ignored

### ISSUE THREAD

**Issue by tmberthold** [sovity/edc-ui#707]
### Description - What happened? *

If an asset is created at the provider via the UI, where path- and query-parameterization is switched on and the necessary data is entered when the consumer initiates the transfer, it appears that the entered data is ignored.

### Expected Behavior *

_See steps to reproduce and attached GIF._

### Observed Behavior *

_See steps to reproduce and attached GIF._

### Steps to Reproduce

- Create asset dialog: enable Path- and Query-Param.;
- set as Base-Path: https://api.hamburg.de
- Create a contract definition.
- second connector: negotiate and start the data transfer
- Transfer-Details:
-- Rest-API POST Endpoint: Webhook.site
-- Custom Subpath: datasets/v1/verkehrslage/collections/verkehrslage/items
-- Custom Query Param: f=json

-> Expected behaviour: JSON from https://api.hamburg.de/datasets/v1/verkehrslage/collections/verkehrslage/items?f=json on Webhook.site
-> Observed behaviour: JSON from https://api.hamburg.de on Webhook.site

### Relevant log output

```shell
no error-logs appear during the whole process
```

### Screenshots

![screen-capture-_3_ (1)](https://github.com/sovity/edc-ui/assets/75306992/a8411a4b-a5c7-4d84-86fa-2819cf853476)

**Comment by AbdullahMuk** [comment]
Bug fix queued for next available capacity.

**Comment by ununhexium** [comment]
Fixed in EDC CE 7.4.0
