### ISSUE TITLE
Fix UI inconsistencies

### ISSUE THREAD

**Issue by ununhexium** [sovity/edc-ui#737]
### Description - What happened? *

The data transfer parametrization options are inconsistent with the backend's capabilities.

### Expected Behavior *

HEAD is not a supported method param. Don't show it.

The UI doesn't indicate that the Content-Type is mandatory when sending a body.

This needs fixing on the frontend side and the backend side.

### Observed Behavior *

Doesn't show impossible choices to the user.

**Comment by SebastianOpriel** [comment]
@ununhexium Was this solved by the PR? Or is the issue still open?

**Comment by ununhexium** [comment]
This was fixed in EDC UI 3.2.2
https://github.com/sovity/edc-ui/blob/main/CHANGELOG.md#v322---2024-04-20
