### ISSUE TITLE
No Default Custom Method.

### ISSUE THREAD

**Issue by ip312** [sovity/edc-ui#739]
### Description - What happened? *

In the paramerization section on the consumer side the Custom Method is currenty not set. The field is just empty.
![grafik](https://github.com/sovity/edc-extensions/assets/91048868/91fe6a50-08b0-45e9-b61f-7fa9fcd3ed92)

### Expected Behavior *

GET method as default.

### Observed Behavior *

If a user forgets to select a method, the connector will be stuck in requesting status forever.
To minimize possible errors, it is best to set a default value.

**Comment by SebastianOpriel** [comment]
Feature itself is no bug, but leads to a bug when no method is chosen, then Connector might lead to an error state.

**Comment by AbdullahMuk** [comment]
@illfixit proposal to improve this situation: make the first option in the dropdown list as default

![Image](https://github.com/user-attachments/assets/68342dbf-2715-4c0d-a694-337bb85eb5dd)

**Comment by SebastianOpriel** [comment]
There was a good reason not to preset GET. Instead please simply make the field mandatory to choose.

**Comment by illfixit** [comment]
I guess it was already solved before

![image](https://github.com/user-attachments/assets/78540051-bdf3-4da6-b3e6-522dbd971add)

![image](https://github.com/user-attachments/assets/1f384edb-5f2a-4612-96f3-9f3248970dc3)
