### ISSUE TITLE
Transfer: Auth header not passed to the API wrapper (for source side)

### ISSUE THREAD

**Issue by bearn01d** [sovity/edc-ui#768]
### Description - What happened? *

When I create an asset with a REST endpoint as the data source and add authentication in the UI, the respective header is not passed to the data source during transfers.

The reason is that the auth information is not passed to the API wrapper on asset creation, specifically it is missing in https://github.com/sovity/edc-ui/blob/cf3b53e99c6876c514a0cea9de3fba71d8ae9885/src/app/core/services/asset-data-source-mapper.ts#L45, although respective fields are defined in `UiDataSource`.

A PR that fixes this is in preparation and will be created later today.

### Expected Behavior *

The auth header is passed to the data source when transferring data.

### Observed Behavior *

The auth header is missing.

### Steps to Reproduce

This can be verified using, for instance, Netcat via `nc -l 8080` on one machine and creating an asset with the data source pointing to this machine's IP on port 8080. When starting a transfer, the headers can be inspected.

### Context Information

> (Added by @AbdullahMuk) Components that were used:
> - edc-ce v9.00
> - edc-ui v4.00

This seems to have been introduced with version 4.0.0.

**Comment by tmberthold** [comment]
Hello an thank you for reporting this.

Could you please add the detailed steps for reproducing, i.e. what was selected and filled in where and how in the UI?

With the following selection in the UI, additional Auth headers do arrive at the data source:
![image](https://github.com/user-attachments/assets/1dac9399-072f-4d58-bb6a-3839dd84be0a)

Data source (here webhook-site selected as demo data-source):
![image](https://github.com/user-attachments/assets/440144d0-1ecb-4bec-9baa-dd2f93f77f0e)

**Comment by bearn01d** [comment]
I did exactly what you did, with the header name `Authorization` and the value `Bearer xyz`.
And I get the following from webhook site:
![image](https://github.com/user-attachments/assets/88d2ad4b-9ce3-4d76-af7c-d248e127dd7a)
I used the release commit of 4.0.0 of the EDC UI. As linked above, from the code it makes sense to me that the header is missing.

**Comment by tmberthold** [comment]
Ah great - thanks for testing again, can confirm it now with the latest release.
Had previously tried EDC CE 7.4.2 and UI 3.2.2, so it has worked before and has just been broken.

Will point to this bug internally.
Thanks also for the PR!

**Comment by richardtreier** [comment]
Fixed with  https://github.com/sovity/edc-ui/pull/772

Thank you for finding this bug!
