### ISSUE TITLE
Contract offer ID is missing on catalog browser view page

### ISSUE THREAD

**Issue by tmberthold** [sovity/edc-ui#795]
# Bug

## Description
`After creating data offer search that data offer in catalog browser using connector endpoint url, When we click on the data offer user should be able to see contract offer id on catalog view page. The idea is that the participant can use the offer id for the API-triggered negotiation.`

## To reproduce:
```
Steps to reproduce the behavior:
- Go to 'Create Data Offer Page'
- Create Data Offer with datasource type "I want to connect to a datasource"
- Create policy and contract definition
- Search data offer catalog browser using connector endpoint url
- Click on data offer
```

## Observed Behaviour
Added by AM on 02.09
- Issue seems to happen after upgrade to [edc-ee v4.0.0](https://github.com/sovity/edc-ee/releases/tag/v4.0.0) / [edc-ui v10.0.0](https://github.com/sovity/edc-ce/releases/tag/v10.0.0)
- Bug successfully reproduced 
   - on connector `https://mds2-2-funtest-jakob.stage-sovity.azure.sovity.io/api/dsp`
![image](https://github.com/user-attachments/assets/50c355c1-40f4-443e-b135-db5f94ee1a65)
   - on connector `https://sovity-demo-b.stage-sovity.azure.sovity.io/api/dsp`

- As comparison, issue does not happen on sovity CaaS on edc-ee v3.6.0 / [edc-ui v9.0.0](https://github.com/sovity/edc-ce/releases/tag/v9.0.0) as tried out with connector `https://sovity-demo-a.stage-sovity.azure.sovity.io/api/dsp`
![image](https://github.com/user-attachments/assets/bbed41d3-3917-4236-bd53-ef0e0e1f917f)

## Expected behavior
`Contract offer id should be present on on catalog browser view page`

```[tasklist]

```

**Comment by AbdullahMuk** [comment]
@illfixit please review my findings in the section `Observed Behaviour`. Please confirm if this bug is frontend related only; based on your feedback we will align further on how to fix it.

**Comment by tmberthold** [comment]
Unfortunately, the content of the ID field is cut off in the UI, which means that not the complete ID is displayed.

UI:
![image](https://github.com/user-attachments/assets/b29d0c98-be6f-4e4d-9bdd-2c9801f797e2)

In reality should be:
`dGVzdHRlc3R0ZXN0dGVzdHRlc3Q=:dGVzdHRlc3R0ZXN0dGVzdHRlc3Q=:MDE5MjA4ZWMtMjI0My03YmEyLWE5ZGYtYzRjZTZkZDEyYzAx`
