### ISSUE TITLE
Create data offer: no info icons & suggestion-text not accurate

### ISSUE THREAD

**Issue by tmberthold** [sovity/edc-ui#811]
### Description - What happened? *

`Info Icon is missing on create data offer and suggestion texts are incorrect`

### Expected Behavior *

`Info Icon should be add on create data offer and suggestion texts should be displayed`

### Observed Behavior *

Create Asset dialog with info-icons:
![image](https://github.com/user-attachments/assets/3ef6d352-8b37-46e3-acb9-cec7024dc189)

Create Data Offer flow without info-icons:
also `Instead of my-asset asset Id should be in suggestion box`
![image](https://github.com/user-attachments/assets/57a83a29-6738-43f6-9769-07221726c6c6)

### Steps to Reproduce

```
Steps to reproduce the behavior:
1. Navigate EDC Application
2. Create Asset
3. Create data offer
```

Compare the input mask of the Create-Asset dialog with the new Create-Data-Offer flow, last one has no info icons.

**Comment by AbdullahMuk** [comment]
Closed because redundant to https://github.com/sovity/PMO-Software/issues/1439

/cc @tmberthold
