### ISSUE TITLE
Dashboard "UI Version" attribute is not updated in 4.1.3

### ISSUE THREAD

**Issue by ip312** [sovity/edc-ui#819]
### Description - What happened? *

I updated the connector using the last release (10.3.0/4.1.3) and noticed that the UI Version in the dashboard is still as old one presented.
![grafik](https://github.com/user-attachments/assets/02ded9e6-7f83-4193-a80e-6193269ac7c9)

### Expected Behavior *

The new UI version.

### Observed Behavior *

![grafik](https://github.com/user-attachments/assets/48940be6-6cba-4a11-be07-b22496e8ea36)

**Comment by tmberthold** [comment]
Is working for me with `image: ghcr.io/sovity/edc-ui:4.1.3` and `image: ghcr.io/sovity/edc-ce-mds:10.3.0`

![image](https://github.com/user-attachments/assets/e3425595-9a57-44f7-966c-ad91529e2e45)

which shows the date of the ui-release for me https://github.com/sovity/edc-ui/releases/tag/v4.1.3

**Comment by ip312** [comment]
I have just updated to 4.1.4 and it presented as expected. I close the issue.
