### ISSUE TITLE
No info-box for contact mail and subject for datasource on-request

### ISSUE THREAD

**Issue by tmberthold** [sovity/edc-ui#820]
### Description - What happened? *

Some information is displayed in info boxes, some directly below an input field.
Should all be in info boxes.

Also please use better dummy-data `suggestion texts are incorrect` .

![image](https://github.com/user-attachments/assets/128be6b5-36ad-46dd-a916-befea597fc09)

### Expected Behavior *

Info Boxes

### Observed Behavior *

Info Text

### Steps to Reproduce

MDS Variant Create Data Offer page

**Comment by illfixit** [comment]
@AbdullahMuk need your input on "Also please use better dummy-data suggestion texts are incorrect ."

**Comment by jkbquabeck** [comment]
Contact email and preferred email subject hint text are not corrected 
<img width="624" alt="image" src="https://github.com/user-attachments/assets/f34f32e9-7922-4f98-8fd7-2bac02006de3">

**Comment by illfixit** [comment]
> Contact email and preferred email subject hint text are not corrected <img alt="image" width="624" src="https://private-user-images.githubusercontent.com/172360733/371960597-f34f32e9-7922-4f98-8fd7-2bac02006de3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTUzMzMsIm5iZiI6MTcyNzg1NTAzMywicGF0aCI6Ii8xNzIzNjA3MzMvMzcxOTYwNTk3LWYzNGYzMmU5LTc5MjItNGY5OC04ZmQ3LTJiYWMwMjAwNmRlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwNzQzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGUyYzNlMGM1Y2MwMTc5NDA4YTZkM2NjYzZhZDllYWI1MDUxY2NhYmFlMzNjMGI3ODIyMzNiZjMzYjMyNGJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QzDHVSrE4u1P8k7rFU0AXIO2128YNRK-kNDavcaKNmA">

doch?
![image](https://github.com/user-attachments/assets/3079ab82-58bd-4324-92c0-60480b7762df)

**Comment by jkbquabeck** [comment]
@illfixit we got feedback: This issue appears on create data offer page, not create asset page.

**Comment by illfixit** [comment]
so the only issue that's left is "please use better dummy-data suggestion texts are incorrect" on Create Data Offer page?

**Comment by jkbquabeck** [comment]
@illfixit correct, this should be a quick update.
