### ISSUE TITLE
Inconsistent renaming "Contract Definition" to "Data Offer" 

### ISSUE THREAD

**Issue by tmberthold** [sovity/edc-ui#831]
### Description - What happened? *

```
- Issue 1 : EDC UI dashboard page we have name mismatch Data offer and contract definitions
- Issue 2 : Incorrect error message displayed "No contract definition found with given filter" when search data offer is not available
- Issue 3 : When we publish new data offer(contract definitions) incorrect error message is displayed
```

### Expected Behavior *

Renaming "Contract Definition" to "Data Offer" in all places

### Observed Behavior *

Inconsistent renaming "Contract Definition" to "Data Offer", see Screenshots for exmaples.

### Screenshots

![image](https://github.com/user-attachments/assets/c0f9c254-18d8-4dfd-b6d7-0a5b29997afa)

![image](https://github.com/user-attachments/assets/63a460bb-6764-4090-b1bb-b4d94093900b)

![image](https://github.com/user-attachments/assets/2e6d3394-f32a-4508-a417-c9d0f715269d)

**Comment by jkbquabeck** [comment]
https://github.com/Mobility-Data-Space/MDS-Project/issues/224#issuecomment-2378975635
Dashboard still needs to be aligned in wording. @illfixit
