### ISSUE TITLE
Sidebar with inconsistent separation in Providing and Consuming sections

### ISSUE THREAD

**Issue by tmberthold** [sovity/edc-ui#836]
### Description - What happened? *

```
As seen on the attached screenshot, the left sidebar is structured in "providing" and "consuming".
This does not really make sense, since elements of the consuming section also contain providing information.
E.g. Contracts is not limited to consuming contracts and the transfer history shows proving as well as consuming transfers.

In this case it would probably better to just list the elements of the sidebar without a separation in a providing and consuming block
```

### Expected Behavior *

see description

### Observed Behavior *

see description/screenshot

### Screenshots

![image](https://github.com/user-attachments/assets/4f8e6600-0b95-423e-8659-a95c5cd8108c)

**Comment by SebastianOpriel** [comment]
We can fix it simply by rearranging:
- Dashboard
- Catalog Browser
- Contracts
- Transfer History
- Provide
  - Create Data Offer
  - Assets
  - Policies
  - Contract Definitions

**Comment by illfixit** [comment]
> We can fix it for the moment simply by rearranging (I might use old names for the navigation bar depending on the screenshot above):
> 
> * Dashboard
> * Catalog Browser
> * Contracts
> * Transfer History
> * Provide
>   
>   * Create Data Offer
>   * Assets
>   * Policies
>   * Contract Definitions
> 
> In the long run, we shall have indeed Consuming and Providing sections, but therefore we need to split up Contracts and Transfer History in consuming / providing.

![Image](https://github.com/user-attachments/assets/49b17ab1-589f-4aea-94de-8739de643ab2)
