### ISSUE TITLE
Contract negotiation fails (goes to an endless loop)

### ISSUE THREAD

**Issue by SrdjanStevanetic** [sovity/edc-ui#888]
### Description - What happened? *

With regard to the UNDERPIN project, we tried to exchange some data between the 2 connectors (AIT and MOH). We created the assets on both connectors with a contract, and the negotiation phase keep going in loop and fails at the end. There are no errors in the browser console, just repeating the request for contract agreement status.

### Expected Behavior *

We would expect the negotiation to succeeds and exchange the data.

### Observed Behavior *

The negotiation never comes to the end, the dialog closes after some time.

### Relevant log output

```shell

```

**Comment by tmberthold** [comment]
Hello, could you give us one or two more information, e.g. are those connectors locally set up EDC CE or are they CaaS and if so which. If local, what do the backend logs say, what do the policies look like etc.?

**Comment by tmberthold** [comment]
@skarampatakis since this is about our CaaS I made this issue a Customer Service Desk ticket. You should receive an e-mail in a second with a link to the ticket, so we can also share more details on the CaaS. I'll close this GH-Issue.
