### ISSUE TITLE
New Asset Creation Page with horizontal (instead of vertical) mat-steps that has prev/next buttons and way more space

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#89]
# Feature Request

## Description

As a USER who creates assets, I want a better UX during the asset creation step on the EDC UI, so I can be efficient during my task. This gains in importance due to 9 new asset properties added to the EDC (https://github.com/sovity/edc-extensions/issues/602). The goal would be to present the properties intuitively structured.

## Which Areas Would Be Affected?

- edc-ui Asset Creation Page

## Why Is the Feature Desired?

_What problems does that user face that existing functionalities do solve?_

Our Asset Creation Dialog is too small. And it will only grow bigger over time. So it's time that the asset creation gets it's own page.

## How does this tie into the current product?

_Describe whether this request is related to an existing workflow, feature, or otherwise something in the product today. Or, does this open us up to new innovative ideas?_

This is tied to https://github.com/sovity/edc-extensions/issues/602

## Stakeholders
- MDS
- @jkbquabeck 
- @SebastianOpriel 
- @sebk46

## Solution Proposal and Work Breakdown

```[tasklist]
### EDC UI
- [ ] New Asset Create Page over the current Asset Create Dialog
- [ ] Create Asset Button opens that page (watch out for how top level routes are defined, we'll need a way to ensure the asset create page does not end up in the main menu).
- [ ] Asset Create Page should contain a horizontal mat steps.
- [ ] Materialize what kind of new MDS fields we have. We need to know what kind of values we are inputting
- [ ] Scout Vy's mock-ups for our ideal Data Offer creation process for possible UX ideas
- [ ] Create a Mock-Up for the new Full-Page Asset Creation Wizard in the sovity Variant (needs to make sense UX-wise)
- [ ] Create a Mock-Up for the new Full-Page Asset Creation Wizard in the MDS Variant (needs to make sense UX-wise)
- [ ] Since we now have a lot of space, try to find reasonable layouting for the inputs with possible description texts or something similar. Also check out how the form looks like when validation errors occur.
- [ ] Implement the page (two pages in the two variants)
- [ ] Improve previous Wizard UX Issue: Check if Pref / Next Buttons could always be at the bottom with just the editable area being scrollable, etc. Find a reasonable solution.
```

**Comment by richardtreier** [comment]
Notes on estimation:
![grafik](https://github.com/sovity/edc-ui/assets/30114507/94bb0d53-96df-4ba7-9fc2-cc98b35d82e0)

**Comment by AbdullahMuk** [comment]
Aligned with @jkbquabeck: deprioritized and out of scope for Q1/2024.

**Comment by SebastianOpriel** [comment]
Solved already
https://github.com/sovity/edc-ui/issues/91
