### ISSUE TITLE
Replace Angular favicon with brand favicon

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#99]
## Feature

Right now we are seeing the default Angular Favicon.

We'd like to have brand-specific favicons.

## Proposed Solution / Breakdown
- [ ] Add a sovity favicon
- [ ] Add an MDS favicon
- [ ] Activate the correct favicon depending on active profile
- [ ] Test the functionality of the favicon properly with private browsing and alternative browsers as favicons are heavily cached / automated. If there's no way to get it to respect the selected favicon depending on profile, we might have to find a way to copy / link the correct file on container startup.

**Comment by SebastianOpriel** [comment]
MDS Favicon: https://raw.githubusercontent.com/Mobility-Data-Space/ids-metadata-broker-open-frontend/main/searchfrontend/public/favicon.ico
